### ISSUE TITLE
Highlighting for True, False & None in Python

### ISSUE THREAD

**Issue by meunierd** [NLKNguyen/papercolor-theme#1]
Right now these special values have the same highlighting as variables.

**Comment by NLKNguyen** [comment]
Thanks for letting me know. I've just fixed it. Right now all Python builtin (including True, False & None) have the same color due to limitation of Python syntax highlighting comes with Vim. I'm looking for alternative plugin support. :)

**Comment by NLKNguyen** [comment]
Check README for the suggested syntax plugin for Python :)

**Comment by meunierd** [comment]
Wow that's great thank you!

**Comment by NLKNguyen** [comment]
You're welcome :smile:

**Comment by jerpint** [comment]
This plugin helped me resolve this issue:

https://github.com/vim-python/python-syntax/
