### ISSUE TITLE
Dark version?

### ISSUE THREAD

**Issue by Phyks** [NLKNguyen/papercolor-theme#10]
Hi,

Do you plan on doing one with a dark background, such as https://equinusocio.github.io/material-theme/ ?

Thanks!

**Comment by pickfire** [comment]
The owner said he will do it, but it is not so important.

**Comment by Phyks** [comment]
I am a big fan of this theme, but could not work decently with a white background =( A dark background would be awesome :)

**Comment by NLKNguyen** [comment]
Wow, that's a nice reference. I'll look into it when I start making the dark theme, and I planned to start in July :)

**Comment by Phyks** [comment]
@NLKNguyen Thanks!

**Comment by wedgwood** [comment]
Looking forward to seeing the dark version :)

**Comment by NLKNguyen** [comment]
Just a couple of weeks :)

**Comment by NLKNguyen** [comment]
The Dark PaperColor Rises :+1:
