### ISSUE TITLE
change background color

### ISSUE THREAD

**Issue by lemon0910** [NLKNguyen/papercolor-theme#101]
hello, your theme is really nice, but I want to change the backgroud color to green,  like Red：199，Green：237，blue：204, so how can do this? thank you

**Comment by NLKNguyen** [comment]
I will work on that to provide overriding options for all colors. I'll update here.

**Comment by lemon0910** [comment]
Thank you for great work

**Comment by NLKNguyen** [comment]
Check out the DESIGN.md doc !

**Comment by NLKNguyen** [comment]
Right now you have provide both the GUI color and 256 color like the doc says. In the future, only one of them is needed.

256 color table: http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html
