### ISSUE TITLE
Unable to use papercolor theme with vim-airline

### ISSUE THREAD

**Issue by babygau** [NLKNguyen/papercolor-theme#11]
Hi @NLKNguyen ,
After putting `let g:airline_theme='papercolor'` in my `.nvimrc`, I got the following errors:

![screenshot](https://cloud.githubusercontent.com/assets/1514823/8228141/cefa80ce-15ef-11e5-8fe7-3d85cd65e9bf.png)

![screenshot](https://cloud.githubusercontent.com/assets/1514823/8228142/d0d6eea0-15ef-11e5-9fb2-8c1787314453.png)

**Comment by groigc** [comment]
The Airline theme on this repository was renamed from `papercolor` to `PaperColor`. You only need to specify the Airline theme in case you are using other colorscheme than PaperColor; otherwise, setting `colorscheme PaperColor` will be enough.

**Comment by babygau** [comment]
Thank you @groigc, it worked :+1:
