### ISSUE TITLE
[REQUEST] Rust syntax highlighting

### ISSUE THREAD

**Issue by Matrix-Zhang** [NLKNguyen/papercolor-theme#110]
as the toipc

**Comment by pickfire** [comment]
I like the syntax highlighting in rust's documentation, which is pretty much well designed.

@NLKNguyen Here are their docs page https://doc.rust-lang.org/ what do you think?

**Comment by NLKNguyen** [comment]
I've added Rust support. Vim 8 recognizes this language by default so no plugin needed. This is the most syntactically complicated language I've ever seen.
