### ISSUE TITLE
[HELP] making help page

### ISSUE THREAD

**Issue by NLKNguyen** [NLKNguyen/papercolor-theme#115]
As PaperColor grows over the years, many features are added and documented in README and other markdown files. Eventually, a proper help page becomes necessary. Moreover, it's a good practice for a Vim plugin. I haven't created any Vim help page and certainly don't know how to make a good one, so I'd like some help adding a help page, maybe based on the existing document written in README.

Also, there was a discussion in Vim project about shipping PaperColor as part of Vim distribution (https://github.com/vim/vim/issues/1665), and a help page is one of the things that PaperColor is missing therefore not ready for shipping.

**Comment by datelligence** [comment]
HI NKyle,  I was looking to message you to say thanks for sharing such a great color theme.  I Installed it,  worked as expected,  and now my VIM IDE looks better.  Thank you,  in doning, so looking to message you, I found this thread asking for contributors,  so I think that is fair to collaborate and I propose my self as a contributor to your wonderful project.

**Comment by NLKNguyen** [comment]
@datelligence Great to hear that you enjoy this color scheme like I enjoy using it myself, which is why I keep improving it when I stumble upon a new set of languages or when users request. The progress is there but nowhere as quick as requests coming in. So, I'm looking forward to your contributions! Thanks :+1:

**Comment by NLKNguyen** [comment]
Solved with #125
