### ISSUE TITLE
Broken syntax highlighting for Python, when switching to other theme.

### ISSUE THREAD

**Issue by folixg** [NLKNguyen/papercolor-theme#116]
When I have a Python file open and switch from PaperColor theme to some other theme, the syntax highlighting doesn't work anymore.

Example:

1. Code as shown with 'default' vim colors.
  ![20180620-092802_scrot](https://user-images.githubusercontent.com/15685939/41658005-a1ef195e-7484-11e8-85e6-5c9625b6e428.png)

2. after `:colorscheme PaperColor`
  ![20180620-092819_scrot](https://user-images.githubusercontent.com/15685939/41658043-c2a38e6e-7484-11e8-92d1-0dfcc7059eb8.png)

3. Code after switching back with `:colorscheme default`
  ![20180620-092835_scrot](https://user-images.githubusercontent.com/15685939/41658075-dfaa8e68-7484-11e8-825f-28c7a7962d59.png)

**Comment by NLKNguyen** [comment]
Try `:e %` to see if the syntax colors come back. This issue is a well-known, but I'm not aware of any fix beside a workaround, or just keep using PaperColor indefinitely :)

**Comment by folixg** [comment]
Interestingly, when switching to PaperColor and back again, after the workaround has been applied once, it doesn't work a second time.
But that's not something I would do very often, therefore I can live with it :)
