### ISSUE TITLE
Is perl syntax intended to have variables and keywords colored as red?

### ISSUE THREAD

**Issue by habamax** [NLKNguyen/papercolor-theme#13]
Other colorschemes make them quite distinct.
ex:
```
use Modern::Perl '2014';
use autodie;
my $world = "hello world from perl"; #my $world is red
$world =~ s/perl/PERL/;
say $world; # red
```

**Comment by NLKNguyen** [comment]
Oh it wasn't designed for Perl yet. I'll look into it soon :)

**Comment by habamax** [comment]
Ah, I see. Thanks in advance!
Btw, this colorscheme is one of the best I have used so far.

**Comment by NLKNguyen** [comment]
Glad to hear that :)
Try out the new update and please let me know how it works out :smiley:

**Comment by pickfire** [comment]
I think colorsheme looks good too, but it doesn't have highlight for ruler and it doesn't support a lot of vim add-ons such as gitgutter, syntastic ...

**Comment by habamax** [comment]
@NLKNguyen thx a lot, it looks perfect now.

**Comment by habamax** [comment]
@pickfire I guess you can create separate issues regarding each individual addons/rulers/etc.

**Comment by NLKNguyen** [comment]
@pickfire I know right, there are so many of them :) but eventually more plugins will be supported depending on the plugin popularity and request. Syntastic seems like a good candidate. 

@habamax Great :+1:
