### ISSUE TITLE
Can I apply the font color of README.md to specific extension name of file

### ISSUE THREAD

**Issue by cs-pchsu** [NLKNguyen/papercolor-theme#134]
I find the font color of README.md very beautiful.
This color configuration seems to be used only in README.md.

Is there a way for me to specify the extension file name.
The file with this extension file name applies this color configuration.

![2019-08-10_000107](https://user-images.githubusercontent.com/21957111/62795095-7e9f1c80-bb08-11e9-9f07-089093fb5001.jpg)

thank you for help

**Comment by cs-pchsu** [comment]
OK，

I find a solution by myself installing a plugin as bellow
https://github.com/plasticboy/vim-markdown#basic-usage

**Comment by NLKNguyen** [comment]
Great! Sorry for the late reply, but glad that you enjoy the theme and found the solution 👍
