### ISSUE TITLE
Blogpost domain expired

### ISSUE THREAD

**Issue by sethwoodworth** [NLKNguyen/papercolor-theme#135]
In your readme the link to your blogpost: http://nlknguyen.com/2015/05/21/vim-paper-color-theme/ goes to an expired domain.  The [Wayback Machine has a copy](https://web.archive.org/web/20160403142726/http://nlknguyen.com/2015/05/21/vim-paper-color-theme/)  Would you prefer to re-host your blog on github pages, or link to the archived copy of your post?

**Comment by NLKNguyen** [comment]
Hi, yeah it's expired, and I forgot to edit the link. The content is actually still hosted on the main server here https://nlknguyen.wordpress.com/2015/05/21/vim-paper-color-theme/

I'm taking note to update it along with the next commit :)
Great finding on the archive website btw. I didn't know that.

Thanks!
