### ISSUE TITLE
Python keywords not highlighted

### ISSUE THREAD

**Issue by MaxG87** [NLKNguyen/papercolor-theme#146]
PaperColor seems to lack support to highlight keywords in Python.

![faulty-highlights](https://user-images.githubusercontent.com/5477952/78874984-7dced980-7a4d-11ea-8c7d-10f8f3f87758.png)

One can see that highlighting of `import` and `not in` works. The others have the colour of plain text only.

**Comment by ea2809** [comment]
If you want the best syntax for python: https://github.com/numirias/semshi

**Comment by pickfire** [comment]
@ea2809 I feel like semshi is using too much colors.

**Comment by MaxG87** [comment]
I just noticed that the problem described here is addressed in the README. Highlighting builtins is disabled by default and must be enabled explicitly. Note that enabling highlighting of builtins required installing the python-syntax plugin for me.
