### ISSUE TITLE
Stops working under MacVim

### ISSUE THREAD

**Issue by szw** [NLKNguyen/papercolor-theme#15]
Hi!

Thanks for a cool theme! After the latest update it stopped working under MacVim. It seems to work in the terminal Vim though. Hope that could be fixed easily.

All the best

szw

**Comment by NLKNguyen** [comment]
I don't have a Mac to try so can you please take a screenshot? Are there errors?

**Comment by szw** [comment]
Sure. Here you have both, MacVim (doesn't work) and terminal (works). No error messages. :/
![zrzut ekranu 2015-07-09 o 01 49 51](https://cloud.githubusercontent.com/assets/341899/8585025/10b9ae98-25dd-11e5-81e0-3d9d7481f681.png)
![zrzut ekranu 2015-07-09 o 01 50 49](https://cloud.githubusercontent.com/assets/341899/8585019/08315c6c-25dd-11e5-9759-c8dca994735a.png)
(terminal might look a bit darker since I have some slight transparency enabled)

**Comment by szw** [comment]
BTW. This weird colors in MacVim are just defaults. So it seems PaperColor hasn't been loaded...? But I'm just guessing.

**Comment by NLKNguyen** [comment]
Try again now

**Comment by NLKNguyen** [comment]
wait, hold on

**Comment by NLKNguyen** [comment]
Ok, it's up there. Hopefully it gets fixed. Also, please try the recently added dark version "PaperColor-Dark" as well and let me know how they work out :)

**Comment by szw** [comment]
Now both work! Thanks :)

**Comment by NLKNguyen** [comment]
Great!!! :+1: Thanks for reporting!
