### ISSUE TITLE
vim-airline dark theme

### ISSUE THREAD

**Issue by bruschill** [NLKNguyen/papercolor-theme#16]
Is there a dark theme for vim-airline in the works? If not, I may take it on myself.

**Comment by NLKNguyen** [comment]
I haven't started yet. Please take it on if you will :) :+1:

**Comment by pickfire** [comment]
I hope that it will be more like the lightline default theme.

**Comment by Grelek** [comment]
How's the dark theme for airline going?

**Comment by bruschill** [comment]
I haven't gotten a chance to start yet, unfortunately. With that said, I'm also colorblind, so I'm not sure how well it'll go haha.

**Comment by pickfire** [comment]
Then it is better to create a theme that looks good to those who have colorblind and ordinary person.

**Comment by NLKNguyen** [comment]
That's interesting. I'm curious to see how it will look :D

**Comment by NLKNguyen** [comment]
How is it going?

**Comment by bruschill** [comment]
Unfortunately I haven't had a lot of time to work on it. I'll see if I can get to it this week and I'll report back.

**Comment by NLKNguyen** [comment]
Ok sure, just take your time :+1:

**Comment by NLKNguyen** [comment]
I guess I'll just go ahead and make it then.

**Comment by bruschill** [comment]
@NLKNguyen I just haven't had the time to put toward this as I would've liked to. My apologies.

**Comment by NLKNguyen** [comment]
No worry :) Thanks for your intention :+1:
