### ISSUE TITLE
Error fetching resource for images that showcase colors in README

### ISSUE THREAD

**Issue by reportaman** [NLKNguyen/papercolor-theme#169]
The sample images for colors are not loaded anymore on the README page, upon clicking the link one gets error: "Error fetching resource".

<img width="1123" alt="Screen Shot 2021-05-08 at 10 52 22 PM" src="https://user-images.githubusercontent.com/71736629/117561986-48c9f780-b050-11eb-844a-2e564feae535.png">

**Comment by NLKNguyen** [comment]
Thanks for reporting. It's been resolved.
