### ISSUE TITLE
Help make it possible to quickly toggle between dark & light variants

### ISSUE THREAD

**Issue by NLKNguyen** [NLKNguyen/papercolor-theme#18]
Ideally only one PaperColor.vim file is needed for both variants. Now there is PaperColor-Dark.vim for dark variant in which the only different is the HEX code of color palette on top of the file.

Would like to be able to use tpope's vim-unimpaired plugin key: `cob` to toggle between dark & light

I tried on this branch of the repo
https://github.com/NLKNguyen/papercolor-theme/blob/unify_both_variants/colors/PaperColor.vim

My attempt is like this:
```VimL
if &background ==  'dark'
    [ dark palette ]
else
    [ light palette ]
endif

[ the rest of syntax color rules ]
```

It works like this in .vimrc file:
```VimL
set background=light
color PaperColor
```
or
```VimL
set background=dark
color PaperColor
```
Also in the command:
`:set background=dark | color PaperColor`
or
`:set background=light | color PaperColor`

However, it doesn't work with vim-unimpaired's `cob` key. Somehow, themes like gruvbox & solarized work with it. I looked at their code but didn't figure out how to make it work for this theme. I didn't expect it to be that tricky.

Need help to make this possible!

**Comment by pickfire** [comment]
I think I can't help you as I don't know vim script. What do you mean `cob`?

**Comment by NLKNguyen** [comment]
It's a key in vim-unimpaired plugin to toggle dark and light variants of a color scheme
https://github.com/tpope/vim-unimpaired/issues/58

It was requested for PaperColor here https://www.reddit.com/r/vim/comments/3cmbar/vim_papercolor_theme_gone_dark/csx4r94

It's alright. I will just keep them separately on the master branch like right now until someone helps to make it work.

**Comment by NLKNguyen** [comment]
Thanks @renechz for solving https://github.com/NLKNguyen/papercolor-theme/pull/20 :+1:
