### ISSUE TITLE
Lua support

### ISSUE THREAD

**Issue by telemachus** [NLKNguyen/papercolor-theme#21]
Thanks for this theme. I'm just getting to know it, but so far I'm enjoying the light version.

> So, if the language you are working on isn't listed here, feel free to make a design request.

I'd love to see Lua support!

**Comment by NLKNguyen** [comment]
Sure, it will be added. I actually thought about adding LUA sometime ago when I first saw LOVE2D. I guess now is the good time to add it :)

**Comment by NLKNguyen** [comment]
I just added it. Check it out. ^^

**Comment by telemachus** [comment]
Sorry not to get back sooner: It looks very good. I used it most of yesterday afternoon, and I'm liking it so far. (I'm red/green colorblind so the basic blues are very good for me. I may fork this and switch a few things though to remove a few choices that confuse me. Would that be ok with you?)

**Comment by NLKNguyen** [comment]
Yes, please go ahead :) I'm totally okay with that.
 Just a heads up,  the built-in LUA syntax file for Vim maps syntax highlighting a little bit oddly compared to syntax files of similar languages  like Python and Ruby.

**Comment by telemachus** [comment]
Thanks for the encouragement and the warning.

**Comment by ajpaulson** [comment]
You might also find the following plugins interesting for Lua support in vim as well as inspiration for things to highlight: 
* https://github.com/xolox/vim-lua-ftplugin
* https://github.com/xolox/vim-lua-inspect
