### ISSUE TITLE
Overriding color choices

### ISSUE THREAD

**Issue by thirtythreeforty** [NLKNguyen/papercolor-theme#26]
First, this is a very pretty color scheme!  I've tried dozens, and this is the first I genuinely like.

However, I do not like the lightened background (df7f3effea61cb509043d614235c9a0243dce7bb); I prefer the old one.  Is it possible for me to override this color in my Vim configuration?  (Because it's a script-scoped variable, I doubt it, but I'm not sure.)  If not, would you be amenable to introducing an option for this?

**Comment by NLKNguyen** [comment]
I came up with this because I couldn't find the one that I genuinely like either :D 

Currently you need to modify the color scheme file, but I would not recommend that because of hassle when updating. Instead, I'll find a way to make customization easier. 

I'm thinking along the line:

```VimL
" .vimrc
let g:PaperColor_Dark_Override = { 'CursorLine' : '#abcdef', 'Background' : '#abcdef' }
```

**Comment by thirtythreeforty** [comment]
I think that would work well, and lend itself well to source control (for dotfiles, etc).

Perhaps you could create a similar list internally, and then simply

    `extend(s:Dark_Colors, g:PaperColor_Dark_Override, "force")

to use the values the user specifies.

**Comment by NLKNguyen** [comment]
I haven't seen that feature before, so I just did it the other way. Check out the recent update!

**Comment by thirtythreeforty** [comment]
Works great, thanks!

**Comment by pickfire** [comment]
Is there support for rainbow parenthesis?

**Comment by NLKNguyen** [comment]
No, it's not possible since the plugin doesn't have highlighting groups to be set by the color scheme. On the other hand, https://github.com/kien/rainbow_parentheses.vim already provides user customization. I can see that the plugin is particularly useful for Lisp like language. I may suggest a customization that match the theme; maybe in the wiki page in the future.

**Comment by pickfire** [comment]
That is too old, look at https://github.com/junegunn/rainbow_parentheses.vim

**Comment by NLKNguyen** [comment]
Oh, I'll take a look when I get the chance.

**Comment by pickfire** [comment]
Try taking a look at nathanaelkane/vim-indent-guides.

**Comment by NLKNguyen** [comment]
That's a cool plugin. I just added support for it.

**Comment by pickfire** [comment]
Maybe I wil try to open an issue for everyone to add suggestion for plugin support, eg. rainbow_parenthesis.vim

**Comment by pickfire** [comment]
There seems to be have some problem as I am using base16. When I use vim-indent-guides:

![2015-07-27-135829_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8899485/a53b20fe-3467-11e5-8dd5-15293aaee942.png)

Sorry, I forgot to used focus.

**Comment by NLKNguyen** [comment]
It's supposed to look like this ![screenshot from 2015-07-26 23 53 37](https://cloud.githubusercontent.com/assets/4667129/8900131/9c6ee0ee-33f1-11e5-9987-59bdfffcf519.png)

I made it alternates between the background color and cursorline color, so there should be no additional color.

**Comment by pickfire** [comment]
So, is there anything wrong with my terminal?

You can take a look at my dotfiles: https://github.com/pickfire/dotfiles

I want to make a prompt for vim-lightline, should I do it?

**Comment by NLKNguyen** [comment]
Did you put `let g:indent_guides_auto_colors = 0` in yet? It's from the plugin instruction.

You have this in your .vimrc, which might cause the problem:
```VimL
" vim-indent-guides
let g:indent_guides_guide_size=1  " vim indent guide size
let g:indent_guides_start_level=2
let g:indent_guides_auto_colors=0
hi IndentGuidesOdd  ctermbg=18
hi IndentGuidesEven ctermbg=19
```

Try replace them with only `let g:indent_guides_auto_colors = 0` instead.

I don't know what a prompt for vim-lightline is. Are you talking about a theme for lightline similar to airline?

**Comment by pickfire** [comment]
It seems like there is a theme for paper color in lightline. https://github.com/itchyny/lightline.vim/commit/967501e7a1cc96ef3aac596741e5ec30dc8ed566

Thanks, it works now after I add `let g:indent_guides_auto_colors = 0`, I hope that it came preconfigured with that.

**Comment by pickfire** [comment]
This is the image preview of papercolor theme in lightline.

![2015-08-03-163232_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/9033813/4e54cd30-39fd-11e5-9d43-2178ed54d43d.png)

Is there any support for https://github.com/mhinz/vim-startify?

**Comment by pickfire** [comment]
Testing video preview with `asciinema`.

[![asciicast](https://asciinema.org/a/2oyramhlycesrylet0vq2ek0a.png)](https://asciinema.org/a/2oyramhlycesrylet0vq2ek0a)

**Comment by NLKNguyen** [comment]
Nice. Can you make a separate issue for Starify? It will be easier for me to remind myself.
