### ISSUE TITLE
Difference between s:red and s:pink so barely visible

### ISSUE THREAD

**Issue by shvetsovdm** [NLKNguyen/papercolor-theme#29]
![screen shot 2015-07-30 at 18 04 51](https://cloud.githubusercontent.com/assets/3574904/8978521/dd6e7a0c-36dd-11e5-9b0b-4cdcc68e09f6.png)

This is your intention?

**Comment by NLKNguyen** [comment]
It's kinda intentional in some languages  I designed for, where s:pink and s:red don't appear next to each other. For example in C++, I use s:pink for type and s:red for include or try/catch. In some other languages, it's unfortunate, and I have yet to find a good solution.

**Comment by NLKNguyen** [comment]
I made the s:red darken a little bit. It does not make much difference though. It has to be red because of design constraint, but there are not many tones available in in 256-color.

**Comment by shvetsovdm** [comment]
![screen shot 2015-08-03 at 7 28 17 pm](https://cloud.githubusercontent.com/assets/3574904/9034790/6f2df6fc-3a0d-11e5-8d01-657544834d7a.png)


In my opinion it looks worse now. Red do not looks like red more like brown. I do not mind how it was before. I'm sorry for what I have created confusion)

**Comment by pickfire** [comment]
I did not notice that `include` is **red** too, I thought it is **light brown**.

**Comment by NLKNguyen** [comment]
I looked at the syntax color in a blog [post](http://jcrowther.io/2015/05/26/using-polymer-webcomponents-with-angular-js/) the other day and thought the dark red would be nice. I will roll the old red color back then.

**Comment by shvetsovdm** [comment]
@NLKNguyen nice, thanks!
