### ISSUE TITLE
Enhance comment readability

### ISSUE THREAD

**Issue by Phyks** [NLKNguyen/papercolor-theme#31]
Hi,

I tried the dark version and I really like it. But I think comments (which are greyish on my screen) are not really readable, especially with a lot of sun and not much backlight, which was also my main concern about molokai.

Perhaps there could be a way to ease comment readability?

![2015-08-03-200939](https://cloud.githubusercontent.com/assets/3856586/9044230/9b87a690-3a1b-11e5-994d-9663d1a942e9.png)

Thanks

**Comment by Phyks** [comment]
Note: Same thing for matching cursor highlight.

**Comment by NLKNguyen** [comment]
The comment color was actually different before the last update. I just tested it out, but now I roll the old color code back :) (it should look greenish like the screenshot)

The paren-matching color is intentionally chosen to be just subtle enough to see the match. If it were high contrast, it would have created a confusion about where the actual cursor is currently at. I see people trying to turn the matching cursor off altogether because of that. I did that too before I knew how to customize a theme.

**Comment by Phyks** [comment]
Thanks for the comments appearance!

Concerning the paren-matching color, in a (too) well lit environment, with not much backlight, I am totally unable to distinguish the matching paren. I think it is good that it is subtle, but it is too subtle, no?

**Comment by NLKNguyen** [comment]
I will add a customizable option for that in the next update and let you know. In the mean time, just use the light variant in that environment then :D The original PaperColor is the light variant which is designed exactly for that purpose.

**Comment by Phyks** [comment]
Thanks!

I am not used to light terminals, but I think I should give it a try in such environments. However, in light variant, my cursor is white on whitish-grey background and not really readable (contrary to dark theme where it is white on grey).

I think this may come from my terminal settings, but is there something that can be done from the theme?

**Comment by NLKNguyen** [comment]
There is none that I know of. The cursor background should be the same color as the foreground of the highlighting group where the cursor is currently at. I guess it's indeed your terminal settings.

**Comment by pickfire** [comment]
Why is the comment **grey**? It is **green** in my terminal.

![2015-08-04-141021_796x861_scrot](https://cloud.githubusercontent.com/assets/4687791/9054337/91de8f5e-3ab2-11e5-9245-2b53f07bdc47.png)

**Comment by NLKNguyen** [comment]
I tried the gray in the previous update. It's back to green now.

**Comment by pickfire** [comment]
I hope that the green can be more easily to distinguish from the code as it currently seems like part of the code. Maybe try making it darker or lighter.

**Comment by NLKNguyen** [comment]
@Phyks I just added `matchparen` customizable option. You can check README for usage :)

**Comment by pabuisson** [comment]
Well I was heading over here to discuss this exact same topic. I was hoping we could maybe have them much less saturated by default, current green looks really distracting to my eye... quite the opposite of @Phyks :) 

Maybe we could try an intermediate value between the current `#5f875f` and the previous attempt using `#808080` ? Or add this as an option, maybe ?

**Comment by NLKNguyen** [comment]
Ok, I'll give it another try and also make it an option ^^

**Comment by pickfire** [comment]
Maybe try something maybe look like a bit **blue** and **green** but not easily distracted by the colour.

**Comment by NLKNguyen** [comment]
I just made it lighter than the last grey color, and it's customizable now. The sample color code for the dark override setting in README is the previous green.

**Comment by pickfire** [comment]
Good job, it looks better now.

**Comment by pabuisson** [comment]
The default looks perfect to me. And the fact that it is customizable is great as well. Thanks a lot :+1:

**Comment by pickfire** [comment]
It sems that `nvim` background colors is a lot lighter than `vim` when using a dark background.

![2015-08-23-200059_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/9428135/cbbcfb74-49d1-11e5-82fc-735460a62e6e.png)
