### ISSUE TITLE
Better dosini filetype syntax highlighting

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#33]
![2015-09-03-213426_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/9659520/95d1d984-5283-11e5-993d-821956bfacf4.png)

I like the current papercolor colour for **dosini** syntax, it just seems that it doesn't highlight the title, eg. `[asdf]`.

**Comment by NLKNguyen** [comment]
Okay, I'll add support for this file type.

**Comment by pickfire** [comment]
Good luck and have a nice day!

**Comment by NLKNguyen** [comment]
I added it. Try it out :)

**Comment by pickfire** [comment]
Thanks, it seems nice for both light and dark background.

Good luck and have a nice day!
