### ISSUE TITLE
Add mail syntax highlighting

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#35]
Hi, I hope you can add syntax highlighting for mail so that I could use the colorscheme in mutt.

Good luck and have a nice day!

**Comment by NLKNguyen** [comment]
There is even a mail file type?!!

How to view it? I need some example to work on. I've never seen this file type.

**Comment by pickfire** [comment]
Solarized seemed to have a nice color.

![2015-09-07-135050_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/9710024/c01fe302-5567-11e5-9340-9c02aa7ecc23.png)

Seems that email is missing.

![2015-09-07-135138_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/9710025/c0d5d360-5567-11e5-94f7-d705e4de8b8e.png)

Unreadable with green text on green background.

![2015-09-07-135248_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/9710027/c1768e54-5567-11e5-9b15-d11152ae3abc.png)

For testing purpose, try `:set ft=mail`.

**Comment by pickfire** [comment]
Maybe we could try to add those screenshots into the wiki.

**Comment by NLKNguyen** [comment]
Can you send me a sample file so I can test?

**Comment by pickfire** [comment]
Sure, http://pastie.org/private/dppzppehlrkbp2zksbayq

And here is the image for solarized light.

**Comment by NLKNguyen** [comment]
I added Mail support for the syntax available in that file. Does this file type have a file extension anyway?



![screenshot from 2015-09-07 12 02 42](https://cloud.githubusercontent.com/assets/4667129/9721902/72537576-5558-11e5-93b5-3de32013a896.png)
![screenshot from 2015-09-07 12 02 23](https://cloud.githubusercontent.com/assets/4667129/9721903/725aa38c-5558-11e5-9eec-811c3c42e7db.png)

I also created a wiki page for code screenshots https://github.com/NLKNguyen/papercolor-theme/wiki/Code-Screenshots
I plan to update the outdated screenshots in README eventually, and I will pick some from this new wiki page.

**Comment by pickfire** [comment]
It seems nice but I still hope you can add color for the *signature* below.

> I added Mail support for the syntax available in that file. Does this file type have a file extension anyway?

I don't know how they used it but I use it without file extension. In My Humble Opinion, I think you shouldn't depend on file extensions as it will break scripts without a file extension.

Did you add support for **restructured text** too?

**Comment by NLKNguyen** [comment]
The built-in mail syntax file doesn't have syntax group for the signature in order to be set.
No worry, I was just curious about the file extension. The color scheme doesn't depend on that. It's always up to user's configuration to set the file type appropriately.

I don't know about restructured text. Perhaps you can create another issue and let me know how to test it.

**Comment by pickfire** [comment]
I am not sure about that but it seems that base16 did that. I think you could try checking https://github.com/chriskempson/base16-vim/blob/master/colors/base16-default.vim#L166 out.

I will create an issue about restructured text later. I think that we should split the color in wiki between light and dark background. Do you agree with it? If you agree, I will do it later.

**Comment by NLKNguyen** [comment]
Can you show a screenshot which the signature has a different color with Base16? I don't know what 'SignColumn' is for, but modifying it doesn't show any different color for me.

Yes, that would be a good idea. Please go ahead and split it :+1:

**Comment by pickfire** [comment]
Maybe that is for Signify. Sorry about the signature, it is the work of `mutt`.

**Comment by pickfire** [comment]
There is still some problem about the `mail` syntax, it seems that papercolor automatically **highlight** the *underline text* in the signature, so it seems weird, is there any support for using papercolor with *italics*, **bold**, `_underline_` or even `blinking`?

![2015-09-09-212348_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/9762915/24f2887a-5739-11e5-9f7a-1c57b7ee581b.png)

**Comment by NLKNguyen** [comment]
Can you check again to see if it's your spelling check turned on?

PaperColor doesn't block italics, underline, or blinking, but it also doesn't use any of them.

**Comment by pickfire** [comment]
> Can you check again to see if it's your spelling check turned on?

Yeah, my spell check is turned on.

This does not happen when I am using base16.

**Comment by NLKNguyen** [comment]
Base16 probably doesn't support it. It's a proper behavior of spelling error detection, not a bug :)

**Comment by pickfire** [comment]
Okay.
