### ISSUE TITLE
bronson/vim-trailing-whitespace fails in neovim

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#37]
In neovim, trailing whitespaces should be red, but instead it turns blacks.

**Comment by NLKNguyen** [comment]
I support this plugin instead https://github.com/ntpeters/vim-better-whitespace. The author said it's inspired by Bronson's one.
On the other hand, I don't focus on Neovim just yet. I wait until it reaches 1.0.

**Comment by pickfire** [comment]
Thanks, it works using https://github.com/ntpeters/vim-better-whitespace.

Can you please tell me what version it currently is? When will it reaches 1.0?

Good luck and have a nice day!

**Comment by NLKNguyen** [comment]
It has a long way to go. Once it reaches 1.0, I'm sure there will be a big announcement, so we'll definitely know very soon after that.

**Comment by pickfire** [comment]
Good speech! When you announce 1.0, I will help you to create some colorscheme for other applications that even base16 does not have (they have slow development currently).

**Comment by NLKNguyen** [comment]
Great!!! ^^
