### ISSUE TITLE
Better Terminal Detection

### ISSUE THREAD

**Issue by meunierd** [NLKNguyen/papercolor-theme#4]
Neovim supports use of true colour in the terminal, but the way papercolor sniffs variables causes it to downgrade to terminal colours (which still look great! I only noticed side by side with gvim). There's an environment variable set for neovim true colour support that you could check.

see:

https://github.com/neovim/neovim/pull/2198

**Comment by NLKNguyen** [comment]
Oh, I will take a look at it when I try out Neovim. Have never used Neovim before :)

**Comment by stoeffel** [comment]
:+1: on that @NLKNguyen you should definitely try neovim

**Comment by NLKNguyen** [comment]
Okay :D everyone is talking about Neovim nowadays. I'll give it a try this weekend.

**Comment by NLKNguyen** [comment]
The colors in terminal Neovim and Vim look identical to me. Do you use mainly gVim or term Vim, @meunierd ?

When I try this (from the link), all colors turn off. I can't get it to work. Any suggestion? 

    $ NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim
![screenshot from 2015-06-07 00 14 19](https://cloud.githubusercontent.com/assets/4667129/8023008/be794c56-0caa-11e5-8cc1-2b6258337f81.png)

I'm still not used to Nevim, but I must say, the embedded terminal is so freaking awesome :)

**Comment by stoeffel** [comment]
It looks good in terminal neovim but in [neovim.app](https://github.com/rogual/neovim-dot-app) not.

* neovim.app
![screen shot 2015-06-07 at 10 24 29](https://cloud.githubusercontent.com/assets/1217681/8023194/840902dc-0cff-11e5-875a-acd5a8b86326.png)

* terminal
![screen shot 2015-06-07 at 10 26 13](https://cloud.githubusercontent.com/assets/1217681/8023203/b64c71de-0cff-11e5-8e4c-2b3a0ecbf770.png)

**Comment by NLKNguyen** [comment]
I see. I haven't found the GUI version for Neovim on Ubuntu yet, probably not available. Could you please check if the same problem occurs with one of the Base16 themes?

**Comment by stoeffel** [comment]
Yop, I think there is no gui for neovim on ubuntu yet. I will try it with a base16 theme asab.

**Comment by stoeffel** [comment]
this is with base16-monokai. The colors look not 100% right (in the terminal). 
I think this is an issue with neovim.
![screen shot 2015-06-08 at 21 54 34](https://cloud.githubusercontent.com/assets/1217681/8043864/19ee78d4-0e29-11e5-860c-b321a7abea8d.png)

**Comment by NLKNguyen** [comment]
Yeah, that's probably it. There is nothing I can do until they improve it. Thanks for testing :)

**Comment by stoeffel** [comment]
Yop, I think you can close this and maybe we should open a issue in neovim or check if it's already known.

**Comment by NLKNguyen** [comment]
Ok, I close it now. I think it's a bit too early considering the fact that they don't even have a standard GUI version yet. It seems more like Neovim.app's issue for now, so yeah it could be helpful if you open an issue there instead. I wouldn't be helpful there because I can't test it (don't have a Mac :smile: )
