### ISSUE TITLE
diffdelete text is unreadable

### ISSUE THREAD

**Issue by wimstefan** [NLKNguyen/papercolor-theme#42]
... since background and foreground colours are the same.

I changed the referring parts (and hopefully didn't mess it up too much ;-)) as you can see below:

```patch
diff --git a/colors/PaperColor.vim b/colors/PaperColor.vim
index 5b9f481..263c67c 100644
--- a/colors/PaperColor.vim
+++ b/colors/PaperColor.vim
@@ -305,7 +305,7 @@ if s:is_dark " DARK VARIANT
   let s:diffadd_fg    = ['#000000', '16']
   let s:diffadd_bg    = ['#5faf00', '70']
 
-  let s:diffdelete_fg = ['#5f0000', '52']
+  let s:diffdelete_fg = ['#000000', '16']
   let s:diffdelete_bg = ['#5f0000', '52']
 
   let s:difftext_fg   = ['#000000', '16']
@@ -385,7 +385,7 @@ else " LIGHT VARIANT
   let s:diffadd_fg    = []
   let s:diffadd_bg    = ['#afffaf', '157']
 
-  let s:diffdelete_fg = ['#ffdfff', '225']
+  let s:diffdelete_fg = []
   let s:diffdelete_bg = ['#ffdfff', '225']
 
   let s:difftext_fg   = []
```

**Comment by pickfire** [comment]
What do you mean `diffdelete`? I think those part that are deleted aren't important.

**Comment by wimstefan** [comment]
Did you read the patch part? There you can see that foreground and background for the DiffDelete highlighting group are the same which makes text unreadable. I think sometimes it's useful or even important to know what exactly is deleted hence my note ....

**Comment by pickfire** [comment]
Can you please show the image?

**Comment by wimstefan** [comment]
Sure.
![screen-invisible-diffdelete](https://cloud.githubusercontent.com/assets/4605934/11263942/9c5f2160-8e8f-11e5-9494-c4f6d23d61e2.png)
![screen-visible-diffdelete](https://cloud.githubusercontent.com/assets/4605934/11263945/a6598138-8e8f-11e5-9f4d-b08f7192538e.png)

**Comment by pickfire** [comment]
It seems like your theme background is too white compare to my vim. Even whiter than neovim.
I thought the place that is highlighted in red should be yellow?

And 

Mine, the default:

![2015-11-19-150513_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/11264578/a4d912d4-8ecf-11e5-8217-afb69521b071.png)

**Comment by wimstefan** [comment]
Hmm interesting ... not sure what causes the difference?
You can find my .vimrc here: [my .vimrc](https://github.com/wimstefan/dotfiles/blob/master/vim/vimrc)

I presume the grade of whiteness doesn't really matter in this context? ;-)

**Comment by pickfire** [comment]
Oh, it seems long, I hope that you can try vim using only pepercolor theme first and find out the problem.

I don't have the time right now.

**Comment by NLKNguyen** [comment]
Hello,
Sorry for late reply, please send me a pull request :)

**Comment by pickfire** [comment]
@wimstefan If I remember correctly, the following plugins doesn't have support with PaperColor theme:

- vim-signify

And it seems weird that the colors should be red in your vimrc. You can take a look at [my .vimrc](https://github.com/pickfire/dotfiles/blob/alarm/home/vimrc).

**Comment by NLKNguyen** [comment]
@wimstefan I think you sent the pull request to your repos instead of this. It doesn't appear in this repos pull request list.

**Comment by wimstefan** [comment]
Ayyyy that is embarassing! And no excuse that I do that the first time :-/
I'll have a look at it as soon as I have a bit more time.
My sincere apologies!

**Comment by wimstefan** [comment]
I hope it went better this time ...

**Comment by NLKNguyen** [comment]
No need to apology, my friend :) and thanks for the request ^^ ddeae4e
