### ISSUE TITLE
Add alternative, vis

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#47]
The vis editor already have an implementation of papercolor theme, I hope that you can add it as an alternative.

https://github.com/jceb/dotfiles/blob/master/config/vis/lexers/themes/papercolor.lua

**Comment by NLKNguyen** [comment]
Interesting. Do you have a screenshot of how it looks with this theme? I'm curious. I didn't even know that editor exists. 
Btw, what do you mean by adding it as an alternative?

**Comment by pickfire** [comment]
@NLKNguyen I don't have a screenshot currently, I suggest you to ask @jceb.

> Btw, what do you mean by adding it as an alternative?

Sorry for not being clear, I think we can just create a link that show https://github.com/jceb/dotfiles/blob/master/config/vis/lexers/themes/papercolor.lua as the port of PaperColor theme to vis.

**Comment by jceb** [comment]
Please find the screenshot attached.  On the left side is "vis" on the
right side vim with the PaperColor theme.


On Mon 18-01-2016 06:15 -0800, Ivan Tham wrote:

> @NLKNguyen I don't have a screenshot currently, I suggest you to ask @jceb.
> 
> > Btw, what do you mean by adding it as an alternative?
> 
> Sorry for not being clear, I think we can just create a link that show https://github.com/jceb/dotfiles/blob/master/config/vis/lexers/themes/papercolor.lua as the port of PaperColor theme to vis.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/NLKNguyen/papercolor-theme/issues/47#issuecomment-172537630

-- 
Jan Christoph Ebersbach
I didn’t want some petty, inferior brand of righteousness that comes
from keeping a list of rules when I could get the robust kind that comes
from trusting Christ - God’s righteousness.  Phil 3:9

**Comment by NLKNguyen** [comment]
Nice one! I'll add a new section in this project README to mention other related projects. Do you plan to have a standalone repository for this in order to link to?

Just a side note, this plugin https://github.com/NLKNguyen/c-syntax.vim enhances the C/C++ syntax for Vim. You may want to try it :)

**Comment by pickfire** [comment]
@NLKNguyen vis doesn't use vim script if I recall correctly.

**Comment by NLKNguyen** [comment]
I understand. That was for Vim.

**Comment by NLKNguyen** [comment]
Added info in README 3c418cbd
