### ISSUE TITLE
ctrlp highlights barely visible

### ISSUE THREAD

**Issue by sappo** [NLKNguyen/papercolor-theme#5]
Hi,
first off, great job! I really like the theme!
I only have on minor issue. If I open ctrlp e.g. `:CtrlPMixed` the current selection is barely visible.

**Comment by NLKNguyen** [comment]
Do you mean the gray background on the whole selected line or the background of the matched text? Can you take a screenshot?

**Comment by sappo** [comment]
The gray background on the whole selected line. 
The screenshot may not seem that bad but on bad notebook screens such as mine :( it's almost invisible.  
![Screenshot of highlighting problem](http://fs1.directupload.net/images/150606/fw6ojij5.png)

**Comment by NLKNguyen** [comment]
I just changed it to be more visible. Let me know if it's better now :)

**Comment by sappo** [comment]
That will work. Thanks!

**Comment by NLKNguyen** [comment]
:smiley: :+1:

**Comment by NLKNguyen** [comment]
Just want to let you know that the default CursorLine color is light grey again, but now you can customize it in your .vimrc file. See the README. The example in there is actually the previous color that I changed for you before, so simply put it in your .vimrc if you still like that light blue color. 

BTW, the dark color scheme is added :)

**Comment by pickfire** [comment]
Maybe change the customization to something like the lightline customization:
![2015-07-13-134130_1596x861_scrot](https://cloud.githubusercontent.com/assets/4687791/8643321/e147dcda-2964-11e5-819b-e95ba9ac0cd8.png)

**Comment by NLKNguyen** [comment]
Good idea, I will try that.

**Comment by NLKNguyen** [comment]
Turned out there are not many requested customizing options, so I'm not focusing on that right now, maybe in the future.

**Comment by NLKNguyen** [comment]
@pickfire btw, I just modified the customization method like the way you suggested.

**Comment by pickfire** [comment]
Thanks.
