### ISSUE TITLE
after installing with Vundle: colorscheme not found

### ISSUE THREAD

**Issue by kjyv** [NLKNguyen/papercolor-theme#58]
Not sure if this is related to the theme, Vundle or my setup. 
Adding Plugin 'NLKNguyen/papercolor-theme' and installing normally with :PluginUpdate, the files are cloned to .vim/bundle fine. It seems though the theme can only be set when the scheme is in .vim/colors/.
It is not in scriptnames otherwise and colorscheme PaperColor throws a can't find color scheme.

**Comment by pickfire** [comment]
@kjyv I use [vim-plug](https://github.com/junegunn/vim-plug) and found no problem using PaperColor after `:PlugUpdate`.

**Comment by kjyv** [comment]
Seems like a nice plugin (I didn't know about it, thanks). But the readme states that Vundle is supposed to work. Probably vim-plug wouldn't put the files in .vim/colors either so not sure if there is something else that needs to be done.

**Comment by pickfire** [comment]
vim-plug put the files in ~/.vim/plugged and add it to the path if I recall correctly.

**Comment by ShengYun** [comment]
Have you restarted vim after plugin update?
If yes check if you enabled PaperColor by
colorscheme PaperColor

It's case sensitive

**Comment by kjyv** [comment]
Apparently, vundle needs to be set up like this, so that was my mistake.

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'NLKNguyen/papercolor-theme'
call vundle#end()
filetype plugin indent on
syntax enable

**Comment by NLKNguyen** [comment]
Glad it's resolved :+1:
