### ISSUE TITLE
The comments have a grey background

### ISSUE THREAD

**Issue by peidong** [NLKNguyen/papercolor-theme#61]
<img width="711" alt="image" src="https://cloud.githubusercontent.com/assets/9426202/14032490/81c221be-f1d0-11e5-8576-12218e6b64a0.png">

The issue happens when I use iTerm in Mac. But when I use vim with GUI, it is good.

**Comment by NLKNguyen** [comment]
Seems like the last commit which changed the comment font-style to Italic caused the problem. I didn't check how it looks in the terminal. I'll reverse the last commit.

Thanks for the feedback!

**Comment by NLKNguyen** [comment]
I just reverted. Please check again.

**Comment by peidong** [comment]
It works, thank you so much!

**Comment by NLKNguyen** [comment]
Great! You're welcome.
