### ISSUE TITLE
Wrong background colour in tmux

### ISSUE THREAD

**Issue by pnth** [NLKNguyen/papercolor-theme#64]
I have tried your colour theme and it works fine on urxvt but in urxvt with tmux, the gray background disappears after the end of each line where the cursor has gone through:

https://ibin.co/2iGICMmiZKzy.png

**Comment by aliceriot** [comment]
This happens for me as well with Vim, but not with NeoVim. Tmux + xfce4-terminal + arch linux.

**Comment by NLKNguyen** [comment]
Could you please check whether any other color scheme, which customizes the background color, have the same problem? I just want to know if it is terminal issue or the theme issue.

**Comment by aliceriot** [comment]
I've noticed the same thing with solarized, if i have the terminal set to solarized light but Vim set to solarized dark. That makes me think it's a Vim + certain terminals issue, since Neovim (in tmux) works fine and has no issues.

**Comment by pnth** [comment]
I got the same problem with solarized. For solarized, I used the author's urxvt and tmux colour setting at ```https://github.com/altercation/solarized```. Maybe you can provide one similar. Currently I set my terminal background similar to your background colour ```URxvt*background: #F0F0F0``` (yours is #f5f5f5), the same way I did for solarized.

**Comment by NLKNguyen** [comment]
I see. Thanks you two for the test. It's likely the terminal / vim issue.
There are other projects listed in the README that might help configuring your terminal theme. One of them is https://github.com/ninrod/dotfiles which provides config for tmux, zsh, and more. The other one https://www.reddit.com/r/vim/comments/36xzbs/vim_paper_color_theme_inspired_by_googles/crqbfpa seems like a quick solution for Urxvt.

**Comment by pnth** [comment]
Thanks for the links

**Comment by pnth** [comment]
This link is a useful fix for vim + tmux background erase issue
http://sunaku.github.io/vim-256color-bce.html

**Comment by NLKNguyen** [comment]
Glad that it's resolved. 
P.S. That web design is just WOW. Thanks for the link.
