### ISSUE TITLE
A similar colorscheme

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#70]
Hi, I think I have found a colorscheme that is somewhat similar to https://github.com/reedes/vim-colors-pencil except the our dark theme isn't that dark.

Maybe we should add it as an alternative?

I think I should also call forth @reedes.

**Comment by reedes** [comment]
Nice color theme!

**Comment by pickfire** [comment]
@reedes thanks, you dark theme looks nice and papercolor's light theme looks nice, are you based on google material design colors too?

**Comment by NLKNguyen** [comment]
Sure, I'm about to add the roadmap for 16-color support first before enabling alternate color palettes in true/256-color, which make it possible to collaborate other color schemes.

Once 16-color support is done, you can already alternate the terminal's color palette for your theme of choice. I posted the guideline http://codepen.io/NLKNguyen/full/NrRpej/ a while ago, and more details and examples come later.

True/256-color for alternative color schemes is a lot trickier though. I'm still thinking about it.

**Comment by NLKNguyen** [comment]
https://github.com/NLKNguyen/papercolor-theme/blob/master/ROADMAP.md

**Comment by reedes** [comment]
Pencil's colors are based on those in iA Writer.
