### ISSUE TITLE
diff under cursorline is barely visible in dark theme

### ISSUE THREAD

**Issue by Bakudankun** [NLKNguyen/papercolor-theme#73]
When `cursorline` is set in diff view, the diff under the cursor line is barely visible like below.

![2016-09-08](https://cloud.githubusercontent.com/assets/4504807/18322068/bdc261c8-756b-11e6-8d54-b6805a8b0691.png)
(look line 5 of left side)

This is same for  added/deleted lines.

**Comment by pickfire** [comment]
![2016-09-08-115509_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/18336626/5ba74e4a-75bb-11e6-85ee-34938bef00d1.png)

This doesn't seem to happen in the light background.

@Bakudankun In My Humble Opinion, I don't think turning on `cursorline` in diff is a nice idea, since you can't see if the line has changed.

**Comment by Bakudankun** [comment]
@pickfire You may be right, but if the cursorline could be rendered "behind" the diff highlighting (see morhetz/gruvbox#40) instead of disabling it, I think it would be so helpful.

**Comment by NLKNguyen** [comment]
I'll look into this soon. I also encountered a similar problem with dark variant when I was refactoring the theme.

**Comment by NLKNguyen** [comment]
Please check again. I've just revised vimdiff colors for both dark and light; more noticeable difference in the dark variant.

**Comment by Bakudankun** [comment]
wow cool!
I like the new coloring so much!

Thank you for your quick work!

![dark](https://cloud.githubusercontent.com/assets/4504807/18497083/71ee009a-7a66-11e6-8499-613ddcf6c679.png)

![light](https://cloud.githubusercontent.com/assets/4504807/18497087/79d0c824-7a66-11e6-814c-bfba63f42498.png)

**Comment by NLKNguyen** [comment]
Anytime :)
