### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by telemachus** [NLKNguyen/papercolor-theme#74]
After updating papercolor this morning (from 867b051 to 5d9d6e1) and starting up neovim, I get this:

    Error detected while processing /Users/telemachus/.config/nvim/bundle/papercolor-theme/colors/papercolor.vim:
    line 1782:
    E746: Function name does not match script file name: PaperColor#Test
    line 1805:
    E746: Function name does not match script file name: PaperColor#GenerateSpecs
    Error detected while processing function <SNR>14_set_highlightings_variable[775]..<SNR>14_HL:
    line   19:
    E684: list index out of range: -1
    E15: Invalid expression: " ctermfg=" . a:fg[-2] " use the 2nd before the last
    Error detected while processing function <SNR>14_set_highlightings_variable[776]..<SNR>14_HL:
    line   19:
    E684: list index out of range: -1
    E15: Invalid expression: " ctermfg=" . a:fg[-2] " use the 2nd before the last
    Error detected while processing function <SNR>14_set_highlightings_variable[777]..<SNR>14_HL:
    line   19:
    E684: list index out of range: -1
    E15: Invalid expression: " ctermfg=" . a:fg[-2] " use the 2nd before the last
    Error detected while processing function <SNR>14_set_highlightings_variable[778]..<SNR>14_HL:
    line   19:
    E684: list index out of range: -1
    E15: Invalid expression: " ctermfg=" . a:fg[-2] " use the 2nd before the last
    Error detected while processing function <SNR>14_set_highlightings_variable[781]..<SNR>14_HL:
    line   19:
    E684: list index out of range: -1
    E15: Invalid expression: " ctermfg=" . a:fg[-2] " use the 2nd before the last
    Error detected while processing function <SNR>14_set_highlightings_variable[782]..<SNR>14_HL:
    line   19:
    E684: list index out of range: -1
    E15: Invalid expression: " ctermfg=" . a:fg[-2] " use the 2nd before the last
    Error detected while processing function <SNR>14_set_highlightings_variable[784]..<SNR>14_HL:
    line   19:
    E684: list index out of range: -1
    E15: Invalid expression: " ctermfg=" . a:fg[-2] " use the 2nd before the last
    Error detected while processing function <SNR>14_set_highlightings_variable[785]..<SNR>14_HL:
    line   19:
    E684: list index out of range: -1
    E15: Invalid expression: " ctermfg=" . a:fg[-2] " use the 2nd before the last
    Error detected while processing function <SNR>14_apply_highlightings:
    line    4:
    E411: highlight group not found: agitStatAdded
    E411: highlight group not found: agitStatRemoved
    E411: highlight group not found: agitDiffAdd
    E411: highlight group not found: agitDiffRemove
    Press ENTER or type command to continue

I'm on OSX 10.11.6, using papercolor with neovim (v0.1.6-83-gc4c2969) in Apple's Terminal.app. Please let me know if there's any other debug information I can give you.

**Comment by NLKNguyen** [comment]
Thanks for the early report. I'll work on this ASAP.

**Comment by NLKNguyen** [comment]
Please check again.

**Comment by telemachus** [comment]
Definitely better! About 80% of the error messages are gone. Here's what remains:

    Error detected while processing /Users/telemachus/.config/nvim/bundle/papercolor-theme/colors/papercolor.vim:
    line 1782:
    E746: Function name does not match script file name: PaperColor#Test
    line 1805:
    E746: Function name does not match script file name: PaperColor#GenerateSpecs
    Press ENTER or type command to continue

**Comment by NLKNguyen** [comment]
Please try again. That error doesn't happen in Vim, but I changed the functions' signature anyway, hopefully that plays nice with NVim.

**Comment by telemachus** [comment]
All clear now! Thanks so much.

**Comment by h-michael** [comment]
I use this theme with neovim.
After update, cannot apply theme, but have no error.

```
:version
NVIM v0.1.6-89-g2daf54e
Build type: Dev
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototype
s -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160912-9977-wzu34e/build/config -I/tmp/neovim-2
0160912-9977-wzu34e/src -I/tmp/neovim-20160912-9977-wzu34e/deps-build/usr/include -I/tmp/neovim-20160912-9977-wzu34e/deps-build/usr/include -I/tmp/neovim-20160912-9977-wzu34e/deps-b
uild/usr/include -I/tmp/neovim-20160912-9977-wzu34e/deps-build/usr/include -I/tmp/neovim-20160912-9977-wzu34e/deps-build/usr/include -I/tmp/neovim-20160912-9977-wzu34e/deps-build/us
r/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160912-9977-wzu34e/build/src/nvim/auto -I/tmp/neovim-20160912-9977-wzu34e/build/include
Compiled by hata-hirokazu@hata-hirokazu.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-2daf54e/share/nvim"
```

**Comment by telemachus** [comment]
@h-michael When you say you "cannot apply theme", what do you mean? What exactly happens?

It looks like you are also on OSX, here's my latest neovim information, as of this morning. I've just updated both neovim and papercolor, and it's working well here.

    :version                                                                        
    NVIM v0.1.6-89-g2daf54e                                                         
    Build type: Dev                                                                 
    Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTI
    FY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-paramet
    er -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-c
    olor=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-2016091
    2-43903-1vw3od1/build/config -I/tmp/neovim-20160912-43903-1vw3od1/src -I/tmp/neo
    vim-20160912-43903-1vw3od1/deps-build/usr/include -I/tmp/neovim-20160912-43903-1
    vw3od1/deps-build/usr/include -I/tmp/neovim-20160912-43903-1vw3od1/deps-build/us
    r/include -I/tmp/neovim-20160912-43903-1vw3od1/deps-build/usr/include -I/tmp/neo
    vim-20160912-43903-1vw3od1/deps-build/usr/include -I/tmp/neovim-20160912-43903-1
    vw3od1/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I
    /usr/include -I/tmp/neovim-20160912-43903-1vw3od1/build/src/nvim/auto -I/tmp/neo
    vim-20160912-43903-1vw3od1/build/include                                        
    Compiled by telemachus@dyn-160-39-198-171.dyn.columbia.edu                      
                                                                                    
    Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
    For differences from Vim, see :help vim-differences                             
                                                                                    
       system vimrc file: "$VIM/sysinit.vim"                                        
      fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-2daf54e/share/nvim"

**Comment by paupalou** [comment]
I have same problem than @h-michael , after update theme is not working in neovim, no errors.

`NVIM 0.1.6-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/build/config -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/src -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-xaQjW3/neovim-0.1.5ubuntu1+git201609131523+2764+21~ubuntu16.04.1/build/include
Compiled by buildd@lcy01-24

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
`

**Comment by pickfire** [comment]
After the latest update, I found papercolor theme working with neovim 0.1.5-1. No errors found so far.

**Comment by h-michael** [comment]
I use dein.vim for plugin manager and nerdtree.
So I look again my rcs.

**Comment by telemachus** [comment]
Since it happens for some, but not all, of us who are using neovim, I'm guessing that it's an interaction with another plugin.

That can be a pain to debug: what I normally do is remove all plugins (except the one I want to test) and then add the others back, one by one. Very annoying if you use a lot of plugins obviously.

**Comment by paupalou** [comment]
hi @telemachus  , i did the test and i think its something about termguicolors, if you create a plain init.vim and add only colorscheme PaperColor works perfect (with the light theme).

If you add set background=dark to to init.vim its forced background=light , did a verbose set background and ....

```
Last set from ~/.config/nvim/colors/PaperColor.vim
```
if you add as 1st line in init.vim set termguicolors all seems fucked up.

Btw , if u grab the theme commit e0fd3ccb15c5cdbc09ecffd39ab9e92cfd7e7406 (5 Aug 2016) all works as expected.

Hope it helps.

**Comment by telemachus** [comment]
@paupalou Right, that's more or less what I do. When I said "remove", I meant "put somewhere else". Renaming the folder they're in puts them somewhere else. :) (I didn't mean that I delete them, though even that wouldn't be such a big deal given that I automate setting up my dotfiles.)

Anyhow, thanks for tracking this down. I suspect you're right: I'm not having the problem, but I don't set `termguicolors`. If I do add that setting, things break. This at least gives @NLKNguyen something to look at.

**Comment by NLKNguyen** [comment]
Thanks for all of your inputs, I'll look into this after installing nvim. Haven't been using nvim for a while.

**Comment by evmorov** [comment]
Confirm that some of the last versions cause errors on neovim and the last one simply doesn't work.

If you use [vim-plug] (https://github.com/junegunn/vim-plug):

1. Edit your .vimrc: `Plug 'NLKNguyen/papercolor-theme', { 'commit': '867b051' }`
2. `:PlugClean`
3. `:PlugInstall`

**Comment by NLKNguyen** [comment]
I added the code to handle NVIM with `termguicolors` option. Please check again to confirm.

**Comment by paupalou** [comment]
hey @NLKNguyen , it seems that now works correctly but some color has changed, for example the background is darker (i prefer it like now btw) , and another color i noticed is the signs at left of line numbers with plugins like vim-signify.

Thanks for fixing

**Comment by telemachus** [comment]
@NLKNguyen Appears to work here for me as well. Thanks for the extra work on this.

**Comment by NLKNguyen** [comment]
You all are welcome. Thanks for the report and details. I'm closing this.

@paupalou Yeah, indeed some colors have changed. I'm revising the whole thing. There were inconsistency between 256 and GUI colors before, but now they are consistent. I'll eventually touch those plugins. One recent change was for vimdiff colors.
