### ISSUE TITLE
Default background is set to light and set background not working

### ISSUE THREAD

**Issue by ShengYun** [NLKNguyen/papercolor-theme#75]
I'm on `d7c9369cb77cf59c782f9a5a6dc3939d6c09e64b` now.

I had 
```
set background=dark
colorscheme PaperColor
```
in my `vimrc` but the colorscheme still loads with the light background, I checked `set background?` is `light`.

Also `set background=dark` or `set background=light` is not working now, I have to first set the background and select the colorscheme to make it work.

**Comment by NLKNguyen** [comment]
What Vim are you using?

I took a piece of code out, which I thought wouldn't have any effect, but probably in some Vim, it matters. I can put that back.

**Comment by taq** [comment]
Using Neovim here, after upgrading the plugin things became crazy on colors. :-(

**Comment by taq** [comment]
Just for record, I reverted back to `867b051d3ad76953d422836445e9f6ce2e95d76c` and now is everything back to normal.

**Comment by ShengYun** [comment]
@NLKNguyen I'm using neovim :)

**Comment by pickfire** [comment]
@taq I am also using neovim, working nice so far with latest papercolor.

**Comment by taq** [comment]
@pickfire I removed all the `bundle` dir commented all the custom configuration on `.vimrc`, and when I just returned `papercolor-theme` there, it messed things up. Weird.
So, me and @ShengYun using Neovim ... on regular Vim, the theme *almost* works fine here on the latest commit I got (not sure there are some other now).

**Comment by skilbjo** [comment]
+1 also experiencing the issue with the latest update. going to revert back

**Comment by jinzhu** [comment]
also broken when using vim 8, using 867b051d3a does fixed the problem.

**Comment by pickfire** [comment]
Maybe there's something wrong with my vim 8.0 and neovim 0.1.5? Everyone reports that papercolor is broken and yet I still find it working nicely on both the raspberry pi and laptop.

**Comment by taq** [comment]
@pickfire are you sure you got the last Papercolor commits? As I told you, I just isolated all my configs and plugins and just adding Papercolor didn't work.

**Comment by pickfire** [comment]
@taq Yes, but I didn't isolate my configs and plugins. I use vim-plug here with quite a few addons.

**Comment by ShengYun** [comment]
I've been looking into this issue, I have the current setup in my `vimrc`
```
set background=dark
colorscheme PaperColor
```

I'm running neovim in tmux in gnome terminal which supports 256 colors, I found that the moment `hi Normal ctermfg=252 ctermbg=234` was executed, by `background` changed from `dark` to `light`.

Not familiar with viml but I'll try to look into what's happening.

This is the test code I used to verify, using the change below, `background` won't be set to `light`

```
fun! s:apply_highlightings()
  " let l:content = []
  for h in s:highlightings
    " call add(l:content, 'hi ' . h[0] . h[1])
    if h[0] == 'Normal'
        continue
    else
        exec 'hi ' . h[0] . h[1]
    endif
  endfor
  " exec join(l:content, "\n")

  " call s:writeToFile(l:content, "highlightings.vim")
endfun
```

**Comment by ShengYun** [comment]
And btw I don't know why the script is loaded 3 times on my machine.

**Comment by alexozer** [comment]
Maybe this was obvious, but I've noticed that placing `set background=dark`
after `colorscheme PaperColor` results in neovim starting with
background=dark. Of course this shouldn't be necessary though.

**Comment by ShengYun** [comment]
@alexozer That would break the airline theme and some other colours.

**Comment by NLKNguyen** [comment]
I think it's fixed now. Please check again.
@ShengYun how do you know it loaded 3 times? Btw, that function is indeed where the fix is located.

**Comment by ShengYun** [comment]
@NLKNguyen Thanks it's fixed now.

I `echom` something in the function then `:message` shows three same things.

```
fun! s:apply_highlightings()
  " Handle background switching right after `Normal` group because of
  " God-know-why reason. It's assumed that the first group in the list
  " is `Normal` group.
  let l:normal = s:highlightings[0]
  exec 'hi ' . l:normal[0] . l:normal[1]
  echom s:is_dark

  " Switching between dark & light variant through `set background`
  if s:is_dark " DARK VARIANT
    set background=dark
  else " LIGHT VARIANT
    set background=light
  endif

  " The rest of syntax highlighting groups 
  for h in s:highlightings[1:]
    exec 'hi ' . h[0] . h[1]
  endfor

endfun
```

![screen shot 2016-09-25 at 10 17 25 pm](https://cloud.githubusercontent.com/assets/1317203/18820698/defd383a-836d-11e6-8754-c94874404734.png)

Btw why does highlighting normal change `background`?

**Comment by NLKNguyen** [comment]
I think it's a Vim defect that in order to switch background correctly in terminal, the background needs to reset after `Normal` group highlighting is set. #20 
Because of that part, the theme is reloaded a couple times which is why the function get called that many times. I took that part out because of this deficiency but didn't test again. Now I just put it back.

Glad it works.

**Comment by taq** [comment]
Yay, fixed, thanks! :-)
