### ISSUE TITLE
Error message on launch

### ISSUE THREAD

**Issue by drzel** [NLKNguyen/papercolor-theme#76]
Vim 8.0.13 throwing below error message with `colorscheme PaperColor` and `set termguicolors`.

```
Error detected while processing function <SNR>80_set_highlight_colors[27]..<SNR>80_add_to_highlight_group:
line    1:
E417: missing argument: ctermfg=
Error detected while processing function <SNR>80_set_highlight_colors[29]..<SNR>80_add_to_highlight_group:
line    1:
E417: missing argument: ctermfg=
```

**Comment by pickfire** [comment]
@drzel Please check previous issues, this might be duplicated. If so, please close this issue.

**Comment by NLKNguyen** [comment]
Are you using the latest one, @drzel ?

**Comment by drzel** [comment]
Yep, I just upgraded my neovim, vim, uninstalled and reinstalled the plugin and found this error occuring in all versions.

**Comment by drzel** [comment]
I can also get the error to appear inside the application by issuing `set background=light / dark`.

**Comment by Leeiio** [comment]
+1
I meet this problem today,my solution is delete `set termguicolors` in you vimrc. Hope it will help you :)

**Comment by NLKNguyen** [comment]
If there is still problem after the merge, I'll reopen the issue.

**Comment by drzel** [comment]
Works great. Thanks!

**Comment by sunaku** [comment]
This issue still occurs for me 😰 under NeoVim 0.2.2 (but not under Vim 8.0) when I use this colorscheme with the [quick-scope plugin](https://github.com/unblevable/quick-scope).  Removing the plugin fixes the problem, so they are somehow incompatible. 🤔
