### ISSUE TITLE
Color override regression

### ISSUE THREAD

**Issue by thirtythreeforty** [NLKNguyen/papercolor-theme#78]
The recent commit 4766a846ba6117d01d1a232f992fa0d21c2e6275 has broken the color-override functionality introduced as a result of #26.

Specifically, I was using the following chunk of VimL to preserve my terminal's translucent background color.

``` vim
" Colorscheme is PaperColor, but change the background
let g:PaperColor_Dark_Override = {
    \ 'background': '#000000',
\ }
colorscheme PaperColor
```

My terminal now becomes opaque when using PaperColor.  I'm not exactly sure what broke.

Alternatively, if there's a better way to do this now, I'd love to hear about it.

**Comment by thirtythreeforty** [comment]
Any comments on this?

**Comment by NLKNguyen** [comment]
Sorry for a very late response, I thought I would take care of this but got caught up on things.
The instruction in README is for version 0.7 and earlier. For the current revision of PaperColor, I haven't done that overriding option yet. It will be available for sure but not soon, I'm afraid.
Once I add it, I will announce here also, so you will get notified.

**Comment by thirtythreeforty** [comment]
So a trivial workaround for this is adding the following autocommand before setting a color theme:

```
autocmd ColorScheme * hi! Normal ctermbg=none guibg=NONE
```

I think this is sufficient for the time being; anyone else feel free to comment and I'll reopen.
