### ISSUE TITLE
PaperColor theme for kakoune

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#81]
Hi, having papercolor ported to http://kakoune.org/ would be nice as the editor seems better than vim in some cases and worse in some cases. Well, I personally doesn't use it much yet as compared to neovim and vis so I am not planning to port it myself.

**Comment by NLKNguyen** [comment]
I don't use that many editors either, so I don't have a plan to port the theme there. My current work on this theme to make it easier to generate for other environments is not progressing because I have some work to do in the moment. I plan to resume next Spring.
