### ISSUE TITLE
"FoldColume" doesn't transparent in tablist

### ISSUE THREAD

**Issue by heelsleeh** [NLKNguyen/papercolor-theme#89]
os: openSUSE
terminal: urxvt
issue:  "FoldColumn"?(i'm not sure this highlight section name) doesn't transparent,see the screenshot below
![heelsleeh-2017-03-19-18 13 33](https://cloud.githubusercontent.com/assets/24011272/24080157/105867ac-0cd4-11e7-87c5-ed443c6d3842.png)

here is my settings of transparent code  in vimrc

let g:PaperColor_Theme_Options = {
  \   'theme': {
  \     'default.dark': {
  \       'transparent_background': 1
  \     }
  \   }
  \ }

**Comment by NLKNguyen** [comment]
Please try again with the latest commit to see if it is solved. I forgot how to display the foldcolumn in Vim, so I just based on the color name.

**Comment by heelsleeh** [comment]
@NLKNguyen thanks for your reply, i tried the latest commit seems got a problem now, when i type vim got a lert like this:

[zosy@heelsleeh ~]$ vim

FoldColumn     xxx term=standout ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
FoldColumn     xxx term=standout ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
Press ENTER or type command to continue

**Comment by NLKNguyen** [comment]
I just fixed the part that caused that error. Please try again. Btw, how to show that grey area?

**Comment by heelsleeh** [comment]
no error but not transparent,  add **set foldcolumn=1** to your .vimrc  to enable it

**Comment by NLKNguyen** [comment]
Please try again now.

**Comment by heelsleeh** [comment]
works fine now, thanks
