### ISSUE TITLE
Show palette

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#9]
Examples:

![solarized palette](https://github.com/altercation/solarized/raw/master/img/solarized-palette.png)
![tomorrow palette](https://github.com/ChrisKempson/Tomorrow-Theme/raw/master/Images/Tomorrow-Night-Bright-Palette.png)

And maybe you could **advertise** more by:

![solarized theme](https://github.com/altercation/solarized/raw/master/img/solarized-yinyang.png)
![solarized theme](https://github.com/altercation/solarized/raw/master/img/solarized-vim.png)
![solarized theme](https://github.com/altercation/solarized/raw/master/img/solarized-selcon.png)
![solarized theme](https://github.com/altercation/solarized/raw/master/img/solarized-dualmode.png)
![solarized theme](https://github.com/altercation/solarized/raw/master/img/solarized-165.png)
![solarized theme](https://github.com/altercation/solarized/raw/master/img/solarized-sym.png)

[Solarized](https://github.com/altercation/solarized) did a good job at advertising and it has good colours too but too bad it has bad support now. I hope you can show the font you are using too.

**Comment by NLKNguyen** [comment]
Thanks for the reference :) There seems to be a lot of work to do that kind of advertising like Solarized, and I don't think I will do it myself :)  Once I make the dark scheme, I will just blog like I did.
I use Meslo font.

**Comment by pickfire** [comment]
What about showing the palette?

**Comment by NLKNguyen** [comment]
Yeah, that is feasible, and it will be after the dark theme is made because I might adjust some colors in the course of making it.

**Comment by pickfire** [comment]
Closing
