### ISSUE TITLE
Is Load_Settings_Override Dead Code?

### ISSUE THREAD

**Issue by robert-claypool** [NLKNguyen/papercolor-theme#92]
I'm not entirely sure about this, but it looks like the [Load_Settings_Override function](https://github.com/NLKNguyen/papercolor-theme/blob/master/colors/PaperColor.vim#L611) is unreachable. Previously, it would be called for an override like this:

```vim
let g:PaperColor_Dark_Override = { 'background' : '#333333', 'cursorline' : '#abcdef' }
```

...but I think that's no longer possible. Load_Settings_Override is not called and there's no alternative way to override the background.

**Comment by NLKNguyen** [comment]
Yes, it's dead code now. There is a new way to override settings as noted in the current README. Not many of the previous options are available yet, but feel free to make a request issue so that I know someone needs that in order to work on :)
