### ISSUE TITLE
Python builtin highlight

### ISSUE THREAD

**Issue by DerWeh** [NLKNguyen/papercolor-theme#94]
The highlighting of builtins with python does not work.

I am using the [python syntax](https://github.com/hdima/python-syntax/) file as specified and have the options:

```
let g:PaperColor_Theme_Options = {
  \   'language': {
  \     'python': {
  \       'highlight_builtins' : 1
  \     },
  \     'cpp': {
  \       'highlight_standard_library': 1
  \     },
  \     'c': {
  \       'highlight_builtins' : 1
  \     }
  \   }
  \ }
"}}}
```

Using a different colorscheme fixes this problem, so it should be an issue of `papercolor`.

**Comment by liuerfire** [comment]
same issue here :-(

**Comment by NLKNguyen** [comment]
@pappasam could you please double check this?

**Comment by NLKNguyen** [comment]
@DerWeh @liuerfire did you put that settings before or after `color PaperColor` ?
The settings have to be before `color PaperColor`.

**Comment by liuerfire** [comment]
@NLKNguyen Oh, it works when put it after `color PaperColor`. Thanks  😄

**Comment by NLKNguyen** [comment]
Great!! You're very welcome 😄

**Comment by pappasam** [comment]
@NLKNguyen just got back from vacation. Glad this was an easy fix though, and sorry for not responding!

**Comment by NLKNguyen** [comment]
@pappasam No worry :) hope it was a nice summer vacation. I got back from mine a few days ago as well 😃
